import Link from "next/link";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import Navbar from "../components/Navbar";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Navbar />
        <div className="px-5 min-lg:px-[50px]">{children}</div>
      </body>
    </html>
  );
}
